services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: testdb
    volumes:
      - ./db-data/:/var/lib/postgresql/
