services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro

volumes:
  postgres_data:
