// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePool(arg1) {
  return window['go']['main']['App']['ClosePool'](arg1);
}

export function DeleteSavedQuery(arg1, arg2) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExportCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCachedMetadata(arg1) {
  return window['go']['main']['App']['GetCachedMetadata'](arg1);
}

export function GetCompletions(arg1) {
  return window['go']['main']['App']['GetCompletions'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2);
}

export function ListColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListColumns'](arg1, arg2, arg3);
}

export function ListSavedQueries(arg1) {
  return window['go']['main']['App']['ListSavedQueries'](arg1);
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListTableChecks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTableChecks'](arg1, arg2, arg3);
}

export function ListTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTableForeignKeys'](arg1, arg2, arg3);
}

export function ListTableIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTableIndexes'](arg1, arg2, arg3);
}

export function ListTableKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTableKeys'](arg1, arg2, arg3);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function LoadSavedQuery(arg1, arg2) {
  return window['go']['main']['App']['LoadSavedQuery'](arg1, arg2);
}

export function PingDatasource(arg1) {
  return window['go']['main']['App']['PingDatasource'](arg1);
}

export function RecordHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecordHistory'](arg1, arg2, arg3, arg4);
}

export function RefreshMetadata(arg1) {
  return window['go']['main']['App']['RefreshMetadata'](arg1);
}

export function RenameQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameQuery'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2, arg3);
}

export function TestDatasource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestDatasource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateDatasource(arg1) {
  return window['go']['main']['App']['UpdateDatasource'](arg1);
}
