// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ListColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListColumns'](arg1, arg2, arg3);
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestDatasource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestDatasource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateDatasource(arg1) {
  return window['go']['main']['App']['UpdateDatasource'](arg1);
}
