// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSavedQuery(arg1:string,arg2:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function GetConfig():Promise<main.Config>;

export function ListColumns(arg1:string,arg2:string,arg3:string):Promise<Array<main.ColumnItem>>;

export function ListSavedQueries(arg1:string):Promise<Array<main.SavedQuery>>;

export function ListSchemas(arg1:string):Promise<Array<main.SchemaItem>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<main.TableItem>>;

export function LoadSavedQuery(arg1:string,arg2:string):Promise<string>;

export function RenameQuery(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveQuery(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestDatasource(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.TestConnectionResult>;

export function UpdateDatasource(arg1:main.Datasource):Promise<void>;
