// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function ClosePool(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string,arg2:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function ExportCSV(arg1:string,arg2:string):Promise<void>;

export function GetAppVersion():Promise<Record<string, string>>;

export function GetCachedMetadata(arg1:string):Promise<main.DatabaseMetadata>;

export function GetCompletions(arg1:string):Promise<main.CompletionSet>;

export function GetConfig():Promise<main.Config>;

export function GetQueryHistory(arg1:string,arg2:number):Promise<Array<main.HistoryEntry>>;

export function ListColumns(arg1:string,arg2:string,arg3:string):Promise<Array<main.ColumnItem>>;

export function ListSavedQueries(arg1:string):Promise<Array<main.SavedQuery>>;

export function ListSchemas(arg1:string):Promise<Array<main.SchemaItem>>;

export function ListTableChecks(arg1:string,arg2:string,arg3:string):Promise<Array<main.CheckItem>>;

export function ListTableForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<main.ForeignKeyItem>>;

export function ListTableIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<main.IndexItem>>;

export function ListTableKeys(arg1:string,arg2:string,arg3:string):Promise<Array<main.TableKeyItem>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<main.TableItem>>;

export function LoadSavedQuery(arg1:string,arg2:string):Promise<string>;

export function PingDatasource(arg1:string):Promise<main.TestConnectionResult>;

export function RecordHistory(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function RefreshMetadata(arg1:string):Promise<main.DatabaseMetadata>;

export function RenameQuery(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveQuery(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestDatasource(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.TestConnectionResult>;

export function UpdateDatasource(arg1:main.Datasource):Promise<void>;
